//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class swapEntities : DbContext
    {
        public swapEntities()
            : base("name=swapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartment> apartment { get; set; }
        public virtual DbSet<apartmentPlacement> apartmentPlacement { get; set; }
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<city_> city_ { get; set; }
        public virtual DbSet<Familiy> Familiy { get; set; }
        public virtual DbSet<familyConstraint> familyConstraint { get; set; }
        public virtual DbSet<familyParameters> familyParameters { get; set; }
        public virtual DbSet<parameter> parameter { get; set; }
        public virtual DbSet<parametersInApart> parametersInApart { get; set; }
        public virtual DbSet<userDetails> userDetails { get; set; }
    }
}
