//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDetails
    {
        public int userId { get; set; }
        public string userPassword { get; set; }
        public string userName { get; set; }
        public Nullable<int> apartmentCode { get; set; }
        public Nullable<int> familyCode { get; set; }
    
        public virtual apartment apartment { get; set; }
        public virtual Familiy Familiy { get; set; }
    }
}
